spring.application.name=API

# CONSERTADO POR CODEX
spring.datasource.url=jdbc:mysql://localhost:3306/stockmaster?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=011225Felix*
# CODEX

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
